version: '3.8'

services:
  ms-persons:
    build:
      context: ./ms-persons  # Directorio donde está el Dockerfile de ms-persons
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my-network

  ms-accounts:
    build:
      context: ./ms-accounts  # Directorio donde está el Dockerfile de ms-accounts
    ports:
      - "8002:8002"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
